[package]
name = "volta"
version = "0.1.0"
edition = "2021"
authors = "Camilo Coelho"
description = "Password Vault ğŸ” built with Rust that runs in the terminal."
repository = "https://github.com/archwebio/volta"
readme = "README.md"
keywords = ["password_manager", "tui"]
license = "MIT"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.5", features = ["derive"]}
color-eyre = "0.6.1"
rand = "0.8.5"
